### ISSUE TITLE
Yuzu-EA-1357 is not rendering video in link's awakening at all while yuzu-mainline can do that

### ISSUE THREAD

**Issue by soredake** [pineappleEA/pineapple-src#8] opened 2021-01-22 08:45 UTC
Maybe some deps is missing in appimage?

![Screenshot_20210122_104219](https://user-images.githubusercontent.com/5204968/105467752-caaf3400-5c9e-11eb-8ab8-e5bda49ee9b8.png)
![Screenshot_20210122_104307](https://user-images.githubusercontent.com/5204968/105467764-cf73e800-5c9e-11eb-91dc-83f60b1717bd.png)

**Comment by MGThePro** [comment] 2021-01-22 10:59
Around EA 1332 they introduced their Buffer Cache Rewrite which brought a huge number of regressions, which is still not merged to Mainline, but Early Access only. I suggest you try a version before that and report back.

ps: It is highly recommended to use OpenGL with yuzu, since their vulkan backend still has quite a few issues like memory leaks

**Closed** 2021-01-25 13:25 UTC
